/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import cryptoExchangePackage.SubSystem;
import cryptoExchangePackage.cryptoExchange;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final cryptoExchange cryptoExchange, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field SubSystem is undefined for the type cryptoExchange"
      + "\nThe method or field Tokens is undefined for the type cryptoExchange"
      + "\nThe method or field TokenNetworks is undefined for the type cryptoExchange"
      + "\nformat cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final SubSystem subSystem, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field TokenPairs is undefined for the type SubSystem"
      + "\nThe method or field Orders is undefined for the type SubSystem"
      + "\nThe method or field SavingOrders is undefined for the type SubSystem"
      + "\nformat cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  public void format(final Object subSystem, final IFormattableDocument document) {
    if (subSystem instanceof XtextResource) {
      _format((XtextResource)subSystem, document);
      return;
    } else if (subSystem instanceof SubSystem) {
      _format((SubSystem)subSystem, document);
      return;
    } else if (subSystem instanceof cryptoExchange) {
      _format((cryptoExchange)subSystem, document);
      return;
    } else if (subSystem instanceof EObject) {
      _format((EObject)subSystem, document);
      return;
    } else if (subSystem == null) {
      _format((Void)null, document);
      return;
    } else if (subSystem != null) {
      _format(subSystem, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(subSystem, document).toString());
    }
  }
}
